// <auto-generated />
namespace ProductsManagementSystemWithMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialData_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialData_test));
        
        string IMigrationMetadata.Id
        {
            get { return "202206060011124_InitialData_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
